sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script: npm run validate
after_success:
  - npm run after-success
  - npm run build-storybook
branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: storybook-static
  github_token: "$GH_TOKEN" # Set in travis-ci.org dashboard
  on:
    branch: master
